package com.neo.redSoap.ghabzino;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2025-11-16T16:26:11.414+03:30
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "Core",
                  wsdlLocation = "ghabzino.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class Core extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Core");
    public final static QName Soap = new QName("http://tempuri.org/", "Soap");
    public final static QName SecureSoap = new QName("http://tempuri.org/", "SecureSoap");
    static {
        URL url = Core.class.getResource("ghabzino.wsdl");
        if (url == null) {
            url = Core.class.getClassLoader().getResource("ghabzino.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(Core.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "ghabzino.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Core(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Core(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Core() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Core(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Core(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Core(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICore
     */
    @WebEndpoint(name = "Soap")
    public ICore getSoap() {
        return super.getPort(Soap, ICore.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICore
     */
    @WebEndpoint(name = "Soap")
    public ICore getSoap(WebServiceFeature... features) {
        return super.getPort(Soap, ICore.class, features);
    }


    /**
     *
     * @return
     *     returns ICore
     */
    @WebEndpoint(name = "SecureSoap")
    public ICore getSecureSoap() {
        return super.getPort(SecureSoap, ICore.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICore
     */
    @WebEndpoint(name = "SecureSoap")
    public ICore getSecureSoap(WebServiceFeature... features) {
        return super.getPort(SecureSoap, ICore.class, features);
    }

}
